### ISSUE TITLE
PWP Capstone Feedback

### ISSUE THREAD

**Issue by mackenzieyoung** [bennypr0fane/pwp-capstones#1]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Great job, your code runs without any errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Very good, your code produces the suite of functions and classes required of it and calls them in an appropriate order.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Nice job, your code is separated into distinct classes and functions, each of which is invoked for its own purpose. Good job using print statements in your methods to print out useful information when you run the code in your populate.py file!
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Good, your code is well-organized and uses Python features appropriately.
 
### Overall Score: 16/16
Excellent work!

**Comment by bennypr0fane** [comment]
Thank you!
